version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kubectl-nuke
    binary: kubectl-nuke
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  replace_existing_draft: true
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## What's Changed
    
    This release includes the following changes:
  footer: |
    ## Installation
    
    ### Quick Install Script
    ```bash
    # Unix-like systems (macOS/Linux)
    curl -fsSL https://raw.githubusercontent.com/codesenju/kubectl-nuke-go/main/install.sh | bash
    
    # Windows (PowerShell)
    Invoke-Expression (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/codesenju/kubectl-nuke-go/main/install.ps1" -UseBasicParsing).Content
    ```
    
    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.
    
    **Full Changelog**: https://github.com/codesenju/kubectl-nuke-go/compare/{{.PreviousTag}}...{{.Tag}}

# Homebrew Cask configuration (skip for prereleases)
homebrew_casks:
  - name: kubectl-nuke
    repository:
      owner: codesenju
      name: homebrew-kubectl-nuke
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/codesenju/kubectl-nuke-go"
    description: "kubectl plugin to forcefully delete Kubernetes resources"
    license: "MIT"
    skip_upload: "{{if .Env.SKIP_HOMEBREW}}{{.Env.SKIP_HOMEBREW}}{{else}}false{{end}}"

# # Winget configuration
# winget:
#   - name: kubectl-nuke
#     publisher: codesenju
#     short_description: "kubectl plugin to forcefully delete Kubernetes resources"
#     description: "A kubectl plugin to forcefully delete Kubernetes resources, including namespaces stuck in the Terminating state. It attempts a normal delete first, and if the resource is stuck, it forcefully removes finalizers."
#     homepage: "https://github.com/codesenju/kubectl-nuke-go"
#     license: "MIT"
#     license_url: "https://github.com/codesenju/kubectl-nuke-go/blob/main/LICENSE"
#     copyright: "Copyright (c) 2024 codesenju"
#     release_notes_url: "https://github.com/codesenju/kubectl-nuke-go/releases/tag/v{{.Version}}"
#     tags:
#       - kubectl
#       - kubernetes
#       - plugin
#       - cli
#     repository:
#       owner: microsoft
#       name: winget-pkgs
#       branch: "kubectl-nuke-{{.Version}}"
#       token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
#       pull_request:
#         enabled: true
#         draft: false
