name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Download Go modules
        run: go mod download
      - name: Build
        run: |
          VERSION=$(git describe --tags --exact-match 2>/dev/null || echo "dev")
          go build -ldflags "-X main.version=$VERSION" -v ./cmd/kubectl-nuke
      - name: Test
        run: go test -v ./...
