name: release-please

on:
  push:
    branches:
      - main
  # Add workflow_dispatch for manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write  # This is critical for PR checks

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go  # Explicitly set release type
          config-file: .config/release-please-config.json
          manifest-file: .config/release-please-manifest.json
          command: github  # Explicit command mode