name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binaries
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-linux-amd64 ./cmd/kubectl-nuke
          GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-linux-arm64 ./cmd/kubectl-nuke
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-darwin-amd64 ./cmd/kubectl-nuke
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-darwin-arm64 ./cmd/kubectl-nuke
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-windows-amd64.exe ./cmd/kubectl-nuke
          GOOS=windows GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o kubectl-nuke-windows-arm64.exe ./cmd/kubectl-nuke
      - name: Archive binaries
        run: |
          tar -czvf kubectl-nuke-linux-amd64.tar.gz kubectl-nuke-linux-amd64
          tar -czvf kubectl-nuke-linux-arm64.tar.gz kubectl-nuke-linux-arm64
          tar -czvf kubectl-nuke-darwin-amd64.tar.gz kubectl-nuke-darwin-amd64
          tar -czvf kubectl-nuke-darwin-arm64.tar.gz kubectl-nuke-darwin-arm64
          zip kubectl-nuke-windows-amd64.zip kubectl-nuke-windows-amd64.exe
          zip kubectl-nuke-windows-arm64.zip kubectl-nuke-windows-arm64.exe
      - name: Generate checksums
        run: |
          sha256sum *.tar.gz *.zip > checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kubectl-nuke-linux-amd64.tar.gz
            kubectl-nuke-linux-arm64.tar.gz
            kubectl-nuke-darwin-amd64.tar.gz
            kubectl-nuke-darwin-arm64.tar.gz
            kubectl-nuke-windows-amd64.zip
            kubectl-nuke-windows-arm64.zip
            checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
